### ISSUE TITLE
Bug: "Unknown opening format: 2" when using no opening book

### ISSUE THREAD

**Issue by bdmendes** [Disservin/fast-chess#132]

**Comment by Disservin** [comment]
Well I wouldnt call it a bug, but I guess the repeated warning calls are quite annoying. If you want to fix the warning I would just create an epd file with the startpos.

**Comment by Disservin** [comment]
@bdmendes I just had a look at your gauntlet script and I think it's flawed. https://github.com/bdmendes/camel/blob/master/gauntlet.sh#L61
All games are played from the start position repeatedly, since you are using no book.

**Comment by bdmendes** [comment]
Yes, I am now realizing you use no book by default. I'll make sure to provide one, but maybe you should make the warning a bit more clearer (and the suggested readme command). Thank you!

**Comment by Disservin** [comment]
I'll add something, thanks for the feedback, also cool fastchess integration. I hope I dont break upstream too often for you ;)

**Comment by bdmendes** [comment]
Well, I'm using one of your tags for now. Hopefully you can package it sometime soon and I can just use the standard distro package manager :)
Thanks for your work
