### ISSUE TITLE
Pass Arguments Directly to `cmd`

### ISSUE THREAD

**Issue by DeveloperPaul123** [Disservin/fast-chess#139]
With `cutechess-cli` it's possible to set the engine command, but also pass arguments directly to it as one would any CLI application. Is it possible to do this with `fast-chess`?

For example, `cutechess-cli` supports this syntax:

`-engine name="MyBot" cmd="Chess-Challenge.exe" arg="uci" arg="MyBot"`

**Comment by Disservin** [comment]
Currently not, but it's not much to add. 
commands need to be passed here https://github.com/Disservin/fast-chess/blob/44254a6672a03f6e78406e259d8d1ecb8cfdff6a/src/third_party/communication.hpp#L119 and here
https://github.com/Disservin/fast-chess/blob/master/src/third_party/communication.hpp#L312

I can have a look later

**Comment by Disservin** [comment]
I have something at https://github.com/Disservin/fast-chess/pull/140, will need to test later on posix.
