### ISSUE TITLE
Child Processes Aren't Always Closed Properly

### ISSUE THREAD

**Issue by DeveloperPaul123** [Disservin/fast-chess#142]
If you don't allow a SPRT run to complete and cancel execution with a keyboard interrupt, the child processes that `fast-chess` spawned continue to run in the background.

**Comment by Disservin** [comment]
I assume on windows? Engines are loosely required to detect EOF's and exit, see https://github.com/official-stockfish/Stockfish/blob/master/src/uci.cpp#L237. 

but yeah this behaviour should be avoided...

**Comment by Disservin** [comment]
If you want you can also give this branch a try, https://github.com/Disservin/fast-chess/tree/fix-windows-process-terminating.

**Comment by DeveloperPaul123** [comment]
> I assume on windows? Engines are loosely required to detect EOF's and exit, see https://github.com/official-stockfish/Stockfish/blob/master/src/uci.cpp#L237.
> 
> but yeah this behaviour should be avoided...

Sorry, yes, this is on Windows 11

**Comment by DeveloperPaul123** [comment]
Though I don't think the UCI implementation I'm using detects EOF's properly

**Comment by DeveloperPaul123** [comment]
> If you want you can also give this branch a try, https://github.com/Disservin/fast-chess/tree/fix-windows-process-terminating.

I'll try to give this a go; but I still haven't been able to get a working build on windows with MSVC or Clang. I've built the binary, but it seems to be broken.

**Comment by DeveloperPaul123** [comment]
> If you want you can also give this branch a try, https://github.com/Disservin/fast-chess/tree/fix-windows-process-terminating.

I tried out this branch in a SPRT run and am getting exceptions:

![image](https://github.com/Disservin/fast-chess/assets/6591180/1453f0d3-024b-4267-9497-e7ef062274e5)
![image](https://github.com/Disservin/fast-chess/assets/6591180/8eebe547-5c5a-4f6e-b3dd-5ae385b72e9c)

Looks like this assert is getting triggered
![image](https://github.com/Disservin/fast-chess/assets/6591180/072935ba-0a57-4602-9907-0f773346096f)

**Comment by Disservin** [comment]
Mh can I get the engine that you are testing with ? This assert is fine for me..

**Comment by DeveloperPaul123** [comment]
[Chess-Challenge.zip](https://github.com/Disservin/fast-chess/files/12664426/Chess-Challenge.zip)
[Scripts.zip](https://github.com/Disservin/fast-chess/files/12664428/Scripts.zip)

I've included the executable along with the script and book I'm using.

**Comment by DeveloperPaul123** [comment]
This very well could be on the engine side

**Comment by Disservin** [comment]
The linked pr should now fix it, thanks. 
I also tried to compile with msvc but I ran into the same error as you... ppl seems to be included by future but I am not sure why it fails to find `_ReturnAddress`

**Comment by Disservin** [comment]
Though I couldnt replicate the issue with the assertion failure.

**Comment by DeveloperPaul123** [comment]
Thanks for the quick fix!
