### ISSUE TITLE
Tournament doesnt end if time losses happen

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#231]
It seems that tournaments doesnt end when a time loss happened. i noticed it when i tested for 8 games, two of those games ended with time losses and when the tournament finished the 8th game, it just gets stuck there still calculating something (i know cuz my laptop fan doesnt wind down) and it doesnt finish the tournament and save to the config file as it usually does.

this is the command i inputted: fast-chess.exe -engine cmd=berserk-13.exe name=Engine1 -engine cmd=Stockfish-dev-20240411-249eec67.exe name=Engine2 -each tc=10+0.1 -rounds 4 -concurrency 4 -report penta=false

**Comment by Disservin** [comment]
introduced by https://github.com/Disservin/fast-chess/commit/57d2d64b9557a9f322afaea438cb7b30adad5d68
