### ISSUE TITLE
update man for sprt

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#233]
```-sprt elo0=ELO0 elo1=ELO1 alpha=ALPHA beta=BETA``` is now ```-sprt elo0=ELO0 elo1=ELO1 alpha=ALPHA beta=BETA model=(logistic/normalized)```

**Comment by Disservin** [comment]
https://github.com/Disservin/fast-chess/commit/8e57cdfbe4dddc85088137909d89fa69c857cb2d
