### ISSUE TITLE
pgn output should be written in pairs instead of individually when -games=2

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#258]
right now the pgn output is written after every game instead of every pair, this is problematic because if someone decides to pause and save a test in the middle of a test, scrapped games can be accidentally included in the pgn.
for example this is the test:
```
C:\Users\Gahtan Syarif Nahdi\Downloads\fast-chess-matchcount5\fast-chess-matchcount5>fast-chess.exe -openings file=openingss.epd format=epd order=sequential -engine cmd=Stockfish-dev-20240413-c55ae376.exe name=Engine1 -engine cmd=Stockfish-dev-20240413-c55ae376.exe name=Engine2 -each tc=10+0.1 -rounds 4 -concurrency 1 -resign movecount=1 score=600 -pgnout file=fastchess.pgn
Starting tournament...
Started game 1 of 8 (Engine1 vs Engine2)
Finished game 1 (Engine1 vs Engine2): 1-0 {Engine2 loses by adjudication}
Started game 2 of 8 (Engine2 vs Engine1)
Finished game 2 (Engine2 vs Engine1): 1-0 {Engine2 wins by adjudication}
--------------------------------------------------
Results of Engine1 vs Engine2:
Elo: -0.00 +/- 0.00, nElo: nan +/- nan
LOS: nan %, DrawRatio: 100.00 %, PairsRatio: nan
Games: 2, Wins: 1, Losses: 1, Draws: 0, Points: 1.0 (50.00 %)
Ptnml(0-2): [0, 0, 1, 0, 0]
--------------------------------------------------
Started game 3 of 8 (Engine1 vs Engine2)
Finished game 3 (Engine1 vs Engine2): 1-0 {Engine2 loses by adjudication}
Started game 4 of 8 (Engine2 vs Engine1)
Finished tournament.
Saved results.
```
i paused it after the first pair so the resulting pgn should only have 2 games (games 1 and 2), but because game 3 has already finished by the time i paused it, it gets included in the output pgn as shown here:
[fastchess.txt](https://github.com/Disservin/fast-chess/files/15033082/fastchess.txt)
the pgn now has 3 games even though the 3rd game should have been scrapped. if i decided to let the test continue id have ended up with a pgn that has more entries than number of games. this is because pgn entries are outputted at every game instead of every pair when -games is set to 2

**Comment by Disservin** [comment]
Mh I dunno I think this is actually the intended behavior

**Comment by gahtan-syarif** [comment]
> Mh I dunno I think this is actually the intended behavior

im not so sure about this, cause you end up getting games that are not part of the pentanomial match statistics being added to the displayed pgns, you end up getting weird stuff like a single round having 3 games. programs like ordo and bayesElo also calculates statistics from the pgns so if we keep the duplicate games it would affect their calculation too

**Comment by gahtan-syarif** [comment]
imo when games are played in pairs the pgnbuilder should only write into the pgn games that are part of finished pairs. i dont know how to modify the code to do this though 😅

**Comment by Disservin** [comment]
Well what if you play very long games idk, 30 minutes each, when I see that the first game has finished I want to be able to view it. What you suggest is that the user should wait for the second game to finish as well. I find that weird and not user friendly?

**Comment by gahtan-syarif** [comment]
> Well what if you play very long games idk, 30 minutes each, when I see that the first game has finished I want to be able to view it. What you suggest is that the user should wait for the second game to finish as well. I find that weird and not user friendly?

to view it the user would have to pause the game first, what this does is it causes the program to essentially redo the first game when the game is unpaused since games from unfinished pairs are not saved to the config file.

**Comment by gahtan-syarif** [comment]
i think this one can be closed at least for now
