### ISSUE TITLE
order=random not working

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#259]
@Disservin is it just me or is order=random not working for opening book? it just plays it sequentially,

here is my prompt: fast-chess.exe -openings file=openingss.epd format=epd order=random -engine cmd=Stockfish-dev-20240413-c55ae376.exe name=Engine1 -engine cmd=Stockfish-dev-20240413-c55ae376.exe name=Engine2 -each tc=10+0.1 -rounds 4 -concurrency 4 -resign movecount=1 score=600 -pgnout file=fastchess.pgn

**Comment by gahtan-syarif** [comment]
https://github.com/disservin/fast-chess/blob/master/src/matchmaking/book/opening_book.cpp seems you forgot to add shuffle()?

**Comment by Disservin** [comment]
oh yeah indeed

**Comment by gahtan-syarif** [comment]
while youre on it i might want to add another bug that i just found, seems if you set the number of rounds to be greater than the number of openings in the book, the test seems to end prematurely, maybe something to do with how the book openings are recycled idk
