### ISSUE TITLE
variant=fischerandom always generates the same FEN

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#268]
when the variant is set to fischerandom and we dont specify an opening book, the FEN that is used for every match is the same FEN which is ```rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w HAha - 0 1```
to get the random starting position right now we have to specify an FRC startpos opening book. ideally the program should generate the random starting position on its own without having to rely on an external book, like cutechess.

**Comment by Disservin** [comment]
mh the behavior is fine with me user should always specify an opening book
