### ISSUE TITLE
-epdout addition?

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#284]
cutechess has -epdout option to output the final fen of each game in an epd file, i think this one is pretty useful for constructing opening books when combined with draw adjudication/resign

**Comment by Disservin** [comment]
Sounds good to me, can they use that alongside the pgnout? Or only one of those can be used

**Comment by gahtan-syarif** [comment]
hmm i didnt really check, but ideally theres no reason why both cant be used at the same time

i dont really know how to code this one so ill leave it to you 😅

**Comment by Disservin** [comment]
> hmm i didnt really check, but ideally theres no reason why both cant be used at the same time
> 
> i dont really know how to code this one so ill leave it to you 😅

Could start by looking at the pgnbuilder and removing everything which isn’t required

**Comment by gahtan-syarif** [comment]
does fast-chess generate a fen after each move? if so we can just print the last move directly into the file

**Comment by Disservin** [comment]
https://github.com/Disservin/fast-chess/blob/master/src/pgn/pgn_builder.cpp#L91

Well are have replayed all moves. After that there’s the last fen, but this should be duplicated in a epdbuilder and everything else should be removed. There isn’t necessarily a place where a new fen is generated after a move.
