### ISSUE TITLE
bugged commit

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#299]
@Disservin i think one of these commits is bugged https://github.com/Disservin/fast-chess/commit/d46317621ebfe6c5e1d4f870593ea1fdbbb06b04 https://github.com/Disservin/fast-chess/commit/6e7d8e64f6ed588ba76ba75140b86ce23220397d

latest master is stuck like this for me, doesnt start any games
![Screenshot 2024-04-28 040502](https://github.com/Disservin/fast-chess/assets/155860115/42528862-81eb-414f-93a1-0c988e60a303)

**Comment by Disservin** [comment]
mh i lowered the ping there but I guess I'll need to check that in the future again
