### ISSUE TITLE
different behaviour of draw and resign adjudication compared to cutechess

### ISSUE THREAD

**Issue by Disservin** [Disservin/fast-chess#335]
vondele saw different results with 
``` 
-draw movenumber=50 movecount=8 score=5 -resign movecount=3 score=600
```
compared to what cutechess outputs

**Comment by gahtan-syarif** [comment]
> vondele saw different results with
> 
> ```
> -draw movenumber=50 movecount=8 score=5 -resign movecount=3 score=600
> ```
> 
> compared to what cutechess outputs

for resignation this is explainable, cutechess has one-sided resignation by default while fastchess only offers two-sided resignation. from cutechess docs
```
     -resign movecount=count score=score [twosided=value]
	     Adjudicate the game as a loss if an engine's score is at least
	     score centipawns below zero for at least count consecutive moves.
	     If value is true (default: false) then activate two-sided resign
	     adjudication.  The winning side's scores must be at least score
	     centipawns above zero for at least count consecutive moves
```

**Comment by gahtan-syarif** [comment]
another reason is resign and draw adjudication in cutechess starts its counter from every odd plies, while in fastchess the counter starts from both odd and even plies @Disservin

**Comment by gahtan-syarif** [comment]
> another reason is resign and draw adjudication in cutechess starts its counter from every odd plies, while in fastchess the counter starts from both odd and even plies @Disservin

for this i think this one might be considered a bug, since if the counter starts counting from an even ply it would start comparing one engine's eval for this move with the eval of the opponent from the previous move

**Comment by gahtan-syarif** [comment]
another reason for the difference: captures and pawn moves reset the adjudicate draw counter in cutechess while in fastchess it doesnt
```
     -draw movenumber=number movecount=count score=score
	     Adjudicate the game as draw if the score of both engines is
	     within score centipawns from zero for at least count consecutive
	     moves, and at least number full moves have been played.  Captures
	     and pawn moves will reset the counters.
```
