### ISSUE TITLE
feature: dedicated file for stderr

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#339]
cutechess has this feature https://github.com/cutechess/cutechess/blob/master/docs/cutechess-cli.6.txt#L273
i think it might be better than just outputting it into the regular log file cause the log file can grow into ridiculous sizes when the number of games are high

**Comment by Disservin** [comment]
Mh I think inside the log is better you will roughly see what happened

**Comment by Disservin** [comment]
Cutechess stderr redirect to a file was perhaps a technical limitation

**Comment by gahtan-syarif** [comment]
i see, makes sense, andrew mentioned something about redirecting stderr to file for OB but i guess using the log can work too
