### ISSUE TITLE
inaccurate pgn comments when multipv>1

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#354]
the pgn comments containing the nodes nps seldepth and centipawn evaluation does not display the main PV info when multipv is set to above 1. you can see in the pgn and log file below where the pgn got its info from the multipv2 info string instead of the multipv1 info string
[log.txt](https://github.com/Disservin/fast-chess/files/15218719/log.txt)
[pgn.txt](https://github.com/Disservin/fast-chess/files/15218720/pgn.txt)
ideally when parsing the info strings we only take information from the multipv1 info string

**Comment by Disservin** [comment]
fixed by https://github.com/Disservin/fast-chess/pull/360
