### ISSUE TITLE
save pgn after every completed game

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#383]
save pgn after every completed game instead of at the end of tournament. cutechess already does this and i think this makes more sense as it safeguards against losing all match data if the system/program crashes. also andrew from OB needed this too i think

**Comment by Disservin** [comment]
what? this isn't the case it might simply not be written because it isnt flushed straight away

**Comment by gahtan-syarif** [comment]
> what? this isn't the case it might simply not be written because it isnt flushed straight away

i just tested again with latest master, and it seems that closing the cmd does save the pgns yeah so some commit might have fixed it. but i notice now a different issue where it prints some pgns of matches that end with illegal bestmoves if you end it this way. oddly enough, this patch seems to fix that behavior too? https://github.com/Disservin/fast-chess/pull/391

**Comment by gahtan-syarif** [comment]
> > what? this isn't the case it might simply not be written because it isnt flushed straight away
> 
> i just tested again with latest master, and it seems that closing the cmd does save the pgns yeah so some commit might have fixed it. but i notice now a different issue where it prints some pgns of matches that end with illegal bestmoves if you end it this way. oddly enough, this patch seems to fix that behavior too? #391

wait nvm
