### ISSUE TITLE
feature: engine config files

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#393]
feature that could be implemented in fast-chess sometime in the future. cutechess allows engine options to be set in a config file, see: https://github.com/cutechess/cutechess/blob/master/docs/cutechess-engines.json.5.txt

**Comment by Disservin** [comment]
you can do the same with the current config?

**Comment by gahtan-syarif** [comment]
the current config is for the entire tournament options, the cutechess engine configs allows to define engine options for each engine specifically, so its two seperate configs

**Comment by Disservin** [comment]
but why would you want two ? you can achieve the behaviour with the current config

**Comment by gahtan-syarif** [comment]
hmm i guess so yeah, ur right
