### ISSUE TITLE
Windows: high memory usage even with low number of rounds

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#439]
![Screenshot 2024-06-11 025013](https://github.com/Disservin/fast-chess/assets/155860115/6b1278ef-c0b1-4488-bdb4-6f07be1125da)

command used:
```
fast-chess.exe -openings file=C:\cutechess-1.3.1-win64\books\UHO_Lichess_4852_v1.epd format=epd -engine cmd="Stockfish dev-20240521-c14b6979.exe" name=Engine1 -engine cmd="Stockfish dev-20240521-c14b6979.exe" name=Engine2 -each proto=uci tc=10+0.1 dir="C:/Chess Engines/" -rounds 10 -concurrency 4 -resign movecount=3 score=600 -pgnout file=fastchess.pgn -ratinginterval 1 -log file=log -randomseed -sprt elo0=0 elo1=5 alpha=0.05 beta=0.05 model=normalized
```
interestingly, in some cases just leaving things alone for long enough the memory usage would suddenly drop down to like 60MB

**Comment by gahtan-syarif** [comment]
> u sure this isnt just the memory for the stockfish engines?

each stockfish instance memory usage is listed seperately on task manager, also i increased the hash size to 32 and it didnt affect the memory usage for fast-chess, see below
![Screenshot 2024-06-11 031227](https://github.com/Disservin/fast-chess/assets/155860115/5931e213-3b9d-4e82-a265-8c8312af419d)

**Comment by vondele** [comment]
The book itself is 167MB and is kept in memory, I assume. If for whatever reason a second copy of it is made, you're at 334MB

**Comment by gahtan-syarif** [comment]
it seems vondele is correct, this is without book:
![Screenshot 2024-06-11 032927](https://github.com/Disservin/fast-chess/assets/155860115/736ca8b0-6cae-4fcf-9883-d5120597cdc5)

but in cutechess interestingly with the lichess book the memory usage is kept at 80MB

**Comment by Disservin** [comment]
Mh the book shouldn’t be in memory twice I’ll have to check how that happens

**Comment by Disservin** [comment]
I think two things are happening.
A) Windows task manager updates slowly the memory usage 
B) the code is a bit suboptimal, i see about ~270MB usage, for the same config, still a bit too much given that the read book should be around 167MB. Still some 100MB short which im currently unsure where that ends up being wasted.

```cpp
        std::ifstream openingFile;
        openingFile.open(file);

        std::string line;
        std::vector<std::string> epd;

        while (util::safeGetline(openingFile, line)) {
            if (!line.empty()) epd.emplace_back(line);
        }

        openingFile.close();

        book_ = epd;
```
This is a bit supoptimal since book is assigned to epd. Just clear the book directly and then write the lines directly into it. You can also call `shrink_to_fit` on each line and on the file vector.

**Comment by vondele** [comment]
I guess std::vector has overhead (i.e. overallocated as to allow for adding to the end effectively without reallocated for every add). Similar probably for std::string.

**Comment by vondele** [comment]
The example https://en.cppreference.com/w/cpp/container/vector/capacity suggests the overhead for a std::vector could essentially be a factor two, but I'm not sure that is realistic, and I assume that an empty std::string is also not taking full space.

**Comment by gahtan-syarif** [comment]
size and capacity of the book seems to be the same:
```
size: 2632036
capacity: 2632036
```

**Comment by Disservin** [comment]
> I guess std::vector has overhead (i.e. overallocated as to allow for adding to the end effectively without reallocated for every add). Similar probably for std::string.

yes that is why i mentioned `shrink_to_fit` which means the vector will be as large as it needs to be and not larger

**Comment by Disservin** [comment]
i wrote some proper improvement here https://github.com/Disservin/fast-chess/pull/441

![image](https://github.com/Disservin/fast-chess/assets/45608332/dad1803d-b72d-4d79-b343-d496fe25114b)

The reason why this is still larger than the book is because of std::string, which internally has a fixed size buffer for SSO.

**Comment by Disservin** [comment]
I think I'll just memory map the file, at least for the EPD case, PGN will eat more memory.
The 40MB are because of the size of a std::string_view in a vector (16 * 2600000 bytes = 41.6 megabytes) 

![image](https://github.com/Disservin/fast-chess/assets/45608332/868b9d66-81af-45cb-8b02-9c0a539c3bd3)

**Comment by Disservin** [comment]
@vondele could you see a potential issue with memory mapping in fishtest environment?

**Comment by vondele** [comment]
not directly, except it is probably not very portable (if we're talking about ` #include <sys/mman.h>` ) ? 

You could probably just store it as 'an array of characters' plus an integer index?

**Comment by Disservin** [comment]
![image](https://github.com/Disservin/fast-chess/assets/45608332/4cb84cc6-7cbb-4b4d-bff4-0fd2fe3504e8)

I guess file + memory for indices is okay, would be 207 MiB in this case. I do wonder what cutechess does actually

**Comment by gahtan-syarif** [comment]
@Disservin for your refactor there might have been a minor bug, i checked the size of the book vector and its listed to be 2632035, while the lichess book itself has 2632036 positions, meaning one position isnt accounted for

**Comment by gahtan-syarif** [comment]
> @Disservin for your refactor there might have been a minor bug, i checked the size of the book vector and its listed to be 2632035, while the lichess book itself has 2632036 positions, meaning one position isnt accounted for

same thing with this:
[startpos_chess960.epd.txt](https://github.com/user-attachments/files/15829189/startpos_chess960.epd.txt)
book vector size is 959 instead of 960

**Comment by gahtan-syarif** [comment]
i think i figured out the issue, the current refactor needs an additional empty line at the end of the epd file to parse the full set of openings, if the last opening is written on the last line, it wont parse it

**Comment by gahtan-syarif** [comment]
closed with https://github.com/Disservin/fast-chess/commit/909660cb7f64b3da622fb50258209b55768b6684
