### ISSUE TITLE
cant build from src

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#469]
MINGW64 /c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess-refactorrand/fast-chess-refactorrand
$ make -j build=release
Fetching submodules..
git submodule init
make: git: No such file or directory
make: *** [Makefile:11: fetch-subs] Error 127

**Comment by Disservin** [comment]
Is that really how you develop ?🤣 but yeah needs a work around

**Comment by gahtan-syarif** [comment]
i dont know how to use git so i just download the zip file extract it and make -j, it seems the new way requires git clone?

**Comment by Disservin** [comment]
tzzzzzzzzzzzzzzzzzz

https://www.youtube.com/watch?v=8lGpZkjnkt4
https://www.youtube.com/watch?v=hwP7WQkmECE

**Comment by Disservin** [comment]
ive added fmt which is a submodule so it requires some different commands, but since fishtest workers dont have a requirement of a git, this won't work the way i imagined it... i will later have to check git subtree and check if that solves it

**Comment by gahtan-syarif** [comment]
ok so downloaded git on msys but it seems it errors for windows?

```
$ make -j build=release
Fetching submodules..
git submodule init
Submodule 'app/third_party/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'app/third_party/fmt'
git submodule update
Cloning into '/c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess/app/third_party/fmt'...
Submodule path 'app/third_party/fmt': checked out 'af8cd4e40425a0f1ed5dbf27c9fc664bf3cf977a'
Done.
echo  -j -- build=release
-j -- build=release
Building..
make -C app BINARY_PATH=/c/Users . Nahdi/Downloads/fast-chess
make[1]: Entering directory '/c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess/app'
make[1]: Nothing to be done for '.'.
make[1]: *** No rule to make target 'Nahdi/Downloads/fast-chess'.  Stop.
make[1]: Leaving directory '/c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess/app'
make: *** [Makefile:6: all] Error 2

```
also how do i clone a specific tree

**Comment by Disservin** [comment]
> ok so downloaded git on msys but it seems it errors for windows?
> 
> ```
> $ make -j build=release
> Fetching submodules..
> git submodule init
> Submodule 'app/third_party/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'app/third_party/fmt'
> git submodule update
> Cloning into '/c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess/app/third_party/fmt'...
> Submodule path 'app/third_party/fmt': checked out 'af8cd4e40425a0f1ed5dbf27c9fc664bf3cf977a'
> Done.
> echo  -j -- build=release
> -j -- build=release
> Building..
> make -C app BINARY_PATH=/c/Users . Nahdi/Downloads/fast-chess
> make[1]: Entering directory '/c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess/app'
> make[1]: Nothing to be done for '.'.
> make[1]: *** No rule to make target 'Nahdi/Downloads/fast-chess'.  Stop.
> make[1]: Leaving directory '/c/Users/Gahtan Syarif Nahdi/Downloads/fast-chess/app'
> make: *** [Makefile:6: all] Error 2
> ```
> 
> also how do i clone a specific tree

can you check if replacing the root_dir in the makefile with `$(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))` works?

> also how do i clone a specific tree

a specific tree? do you mean branch? `git checkout <name>`

**Comment by gahtan-syarif** [comment]
ahh yeah branch i meant,

also changing the root dir doesnt seem to work

**Comment by Disservin** [comment]
for whatever reason it thinks your path is `/c/Users . Nahdi/Downloads/fast-chess` just got rid of most of your name lol

**Comment by gahtan-syarif** [comment]
is it because of the space in my name? in unix spaces arent allowed in directories right?

**Comment by Disservin** [comment]
nah you can, it just needs to be escaped when used
```
mkdir "foo bar"
cd foo\ bar
```

**Comment by Disservin** [comment]
does this work?
```diff
diff --git a/Makefile b/Makefile
index 708dbe9..9d3d8bf 100644
--- a/Makefile
+++ b/Makefile
@@ -25,7 +25,7 @@ update-man: man ## Update man like page

 tests: fetch-subs ## Run tests
        @echo "Running tests.."
-       $(MAKE) -C app tests BINARY_PATH=$(ROOT_DIR)
+       $(MAKE) -C app tests BINARY_PATH=../
        @echo "Done."

 format: ## Format code
```

**Comment by gahtan-syarif** [comment]
yeah, that works
