### ISSUE TITLE
make trace logger output exclusively on the log file and not the command line

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#476]
currently, with how much trace logger output is available, running log level=trace makes the log output on the command line exceedingly large making it impossible to discern any information, see below: 
https://github.com/Disservin/fast-chess/assets/155860115/fc677046-015c-4d3a-9108-1c4a04c37c3e

perhaps a better way would be to make the trace logger output print exclusively on the log file?

**Comment by gahtan-syarif** [comment]
or on second thought... maybe just remove the "pinging engine" and "engine is responsive" log outputs as thats 99% of the bulk. and replace them with "engine cant be pinged" and "engine is not responsive" only when the engine crashes

**Comment by Disservin** [comment]
i dont think this is the correct way, i think we should rather have everything more severe than info be printed to the console, and the other stuff like trace only goes in the log file

**Comment by gahtan-syarif** [comment]
> i dont think this is the correct way, i think we should rather have everything more severe than info be printed to the console, and the other stuff like trace only go in the log file

logger::info should always also be printed to the command line as fishtest relies on some of the log outputs there. also has the "sprt finished" message. for trace yeah it can just go to the log file
