### ISSUE TITLE
feat: add engine gauntlets

### ISSUE THREAD

**Issue by AlexBrunetti** [Disservin/fast-chess#488]
Hi,
To run a gauntlet, should I conduct a separate tournament for each opponent, or is there a more efficient method?

Thanks,
Alex

**Comment by gahtan-syarif** [comment]
> Hi, To run a gauntlet, should I conduct a separate tournament for each opponent, or is there a more efficient method?
> 
> Thanks, Alex

yes, you need to create a seperate tournament for each opponent, fast-chess as of latest dev does not support tournaments with greater than two engines

**Comment by AlexBrunetti** [comment]
The latest release 0.8.2 does, indeed. In any case, do you recommend always using the latest dev version instead of the latest rel?

**Comment by gahtan-syarif** [comment]
> The latest release 0.8.2 does, indeed. In any case, do you recommend always using the latest dev version instead of the latest rel?

personally i would recommend the current latest dev as it has a lot of bugfixes (especially in match adjudication) and tons of new features, but release 0.8.2 is still usable

**Comment by AlexBrunetti** [comment]
May thanks.

Alex
