### ISSUE TITLE
Dealing with invalid options..

### ISSUE THREAD

**Issue by vondele** [Disservin/fast-chess#535]
when passing `option.FooBar=11` to an engine that doesn't have it, cutechess-cli will warn as in :
```
Warning: New-ee6fc7e38b4aeef44862159215a56d97122f59a0 doesn't have option FooBar
```

If an existing option has an invalid value cutechess-cli will warn as in:
```
Warning: Invalid value for option Hash: -16
```

fishtest checks these warning messages:
https://github.com/vondele/fishtest/blob/bf62adf674e97ac69229aa879beb215c32d91ba6/worker/games.py#L1004-L1014

**Comment by gahtan-syarif** [comment]
curretly we have this https://github.com/Disservin/fast-chess/blob/8115d51b94d80ce9104c4e2fe8722832765daaf4/app/src/engine/uci_engine.cpp#L173-#L175 but it doesnt work for some reason, possibly because stockfish doesnt stderr?

**Comment by vondele** [comment]
must be a cutechess check based on the `uci` output. SF doesn't generate such warning.

**Comment by Disservin** [comment]
> but it doesnt work for some reason, possibly because stockfish doesnt stderr?

it only checks if the string was successfully send to the engine? there is no validation

**Comment by vondele** [comment]
A (non-critical) TODO for 
https://github.com/official-stockfish/fishtest/pull/2119

**Comment by Disservin** [comment]
should be fixed by the linked pr, should also have the same output syntax as cutechess
