### ISSUE TITLE
opening order default

### ISSUE THREAD

**Issue by vondele** [Disservin/fast-chess#546]
Openings will be picked in the order specified by ORDER,
			which can be either 'random' or 'sequential' (default).

vs 

               ORDER  - the order of openings to be played, either random or sequential.
                         Default is random.

**Comment by robertnurnberg** [comment]
Noting here that if default behaviour is changed, then parts of https://github.com/Disservin/fast-chess/pull/448 should be reverted again.

**Comment by gahtan-syarif** [comment]
i think random for default makes more sense as its the one testers typically use, and fishtest also already specifies `order=random`

**Comment by vondele** [comment]
I'm find with any default as long as the choice is conscious.
