### ISSUE TITLE
output message order at very fast time control

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#554]
when concurrency is high and the tc is fast (1 second or below), the output order can occasionally be chaotic, ex:
```
Finished game 187 (Engine1 vs Engine2): 0-1 {White loses on time}
Finished game 186 (Engine2 vs Engine1): 0-1 {White loses on time}
Score of Engine1 vs Engine2: 95 - 92 - 0  [0.508] 187
Score of Engine1 vs Engine2: 94 - 92 - 0  [0.505] 186
```

might need to fix this if we want to switch to using faster time controls in fishtest

**Comment by vondele** [comment]
A critical TODO for https://github.com/official-stockfish/fishtest/pull/2119
