### ISSUE TITLE
Throw error when opening book seed is not specified

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#572]
i notice engine devs have a bad habit of not specifying the book seed or randomseed on tests. theres currently a warning for it but they tend to ignore this. making a pr soon

**Comment by robertnurnberg** [comment]
Wouldn't this go against the spirit of having order default to random. That would rather suggest to use randomseed as default, too. It's a design decision. Maybe now is the right time to think carefully of what is best. Options are to leave master as is, follow exactly what cute-chess is doing, or mandating order and seed to be specified.

**Comment by gahtan-syarif** [comment]
my thinking is to make the seed specification mandatory only when the order is random

**Comment by robertnurnberg** [comment]
And random is currently the default? Hence my point.

**Comment by Disservin** [comment]
What is wrong with not specifying one?

**Comment by gahtan-syarif** [comment]
> What is wrong with not specifying one?

concerns of overfitting to the first N openings of the book, as with the default seed the opening sequences doesnt change after each test. also having opening book seed randomized by default makes the behavior consistent with cutechess, which is necessary for the cutechess build
