### ISSUE TITLE
PGN TC output difference

### ISSUE THREAD

**Issue by vondele** [Disservin/fast-chess#584]
Not so critical, nor do I know what is better but:

For 
```
                -engine name=sf_1 tc=inf depth=6 cmd=./sf_1 dir=.\
                -engine name=sf_2 tc=inf depth=8 cmd=./sf_2 dir=.\
```
cc
```
[BlackTimeControl "inf"]
[WhiteTimeControl "inf"]
``` 
vs fc
 ```
[TimeControl "-"]
```

**Comment by gahtan-syarif** [comment]
> Not so critical, nor do I know what is better but:
> 
> For
> 
> ```
>                 -engine name=sf_1 tc=inf depth=6 cmd=./sf_1 dir=.\
>                 -engine name=sf_2 tc=inf depth=8 cmd=./sf_2 dir=.\
> ```
> 
> cc
> 
> ```
> [BlackTimeControl "inf"]
> [WhiteTimeControl "inf"]
> ```
> 
> vs fc
> 
> ```
> [TimeControl "-"]
> ```

fast-chess one follows the pgn standard

**Comment by gahtan-syarif** [comment]
for this one id much prefer if we stick to the fast-chess version as the pgn standard is clear that when there is no enforced time control the time control tag should display a dash http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c9.6.1

also as for the `WhiteTimeControl` and `BlackTimeControl` , its used by cutechess and fastchess when the time control of black and white is different, in the case thats listed above its a clear bug on cutechess side as the timecontrol for both sides are the same

**Comment by vondele** [comment]
not so clear, since white and black have different depth ... which isn't directly visible. But yeah, I agree, grey zone.

**Comment by gahtan-syarif** [comment]
yeah, depth might be different, but it isnt really a timecontrol as its not enforced, in human terms its just one engine deciding to "think" more

**Comment by Disservin** [comment]
> not so clear, since white and black have different depth ... which isn't directly visible. But yeah, I agree, grey zone.

does removing the depth argument lead to only one timecontrol?

**Comment by vondele** [comment]
specifying equal depths leads to one timecontrol.

**Comment by gahtan-syarif** [comment]
reported this to cutechess repo, lets see if they'll fix it

**Comment by gahtan-syarif** [comment]
alwey from cutechess has responded and it seems this behavior is a lack of refinement in cutechess side, so i think this can be closed
