### ISSUE TITLE
bugged commit

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#586]
@Disservin from latest ci
```
fast-chess.exe -openings file=C:\cutechess-1.3.1-win64\books\UHO_Lichess_4852_v1.epd -engine cmd="Stockfish dev-20240709-362a77a3.exe" name=Engine1 -engine cmd="Stockfish dev-20240709-362a77a3.exe" name=Engine2 -each proto=uci nodes=30000 dir="C:/Chess Engines/" -rounds 4 -concurrency 4 -resign movecount=3 score=600 -pgnout file=fastchess.pgn -ratinginterval 1 -log file=log -recover
Warning: No opening book seed specified! Consider specifying one, otherwise the match will be played using the default seed of 951356066.
Indexing opening suite...
terminate called without an active exception
terminate called recursively
terminate called recursively
terminate called recursively
```

**Comment by Disservin** [comment]
dunno need some more info here all looks fine in the ci and on my side

**Comment by gahtan-syarif** [comment]
> dunno need some more info here all looks fine in the ci and on my side

it started from this one https://github.com/Disservin/fast-chess/actions/runs/9944283341

**Comment by gahtan-syarif** [comment]
maybe windows only problem?
log doesnt show anything after "indexing opening suite..."

**Comment by Disservin** [comment]
how do the lines in the opening book look like?

**Comment by gahtan-syarif** [comment]
> how do the lines in the opening book look like?

rnb1kbnr/ppp1pppp/8/4q3/8/2N5/PPPP1PPP/R1BQKBNR w KQkq - hmvc 2; fmvn 4;
rnbqkbnr/pp2pppp/2p5/8/2pP4/4P3/PP3PPP/RNBQKBNR w KQkq - hmvc 0; fmvn 4;
rnbqk1nr/pppp1ppp/3b4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - hmvc 0; fmvn 3;

**Comment by Disservin** [comment]
ah looks like i was too fast..
https://github.com/Disservin/chess-library/actions/runs/9944268080/job/27469957968

**Comment by vondele** [comment]
if it makes sense to compare against cutechess for .epd file of this form, it is easy to add another round to the testing script.

**Comment by Disservin** [comment]
Always happy about tests🙃

**Comment by vondele** [comment]
> > how do the lines in the opening book look like?
> 
> rnb1kbnr/ppp1pppp/8/4q3/8/2N5/PPPP1PPP/R1BQKBNR w KQkq - hmvc 2; fmvn 4; rnbqkbnr/pp2pppp/2p5/8/2pP4/4P3/PP3PPP/RNBQKBNR w KQkq - hmvc 0; fmvn 4; rnbqk1nr/pppp1ppp/3b4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - hmvc 0; fmvn 3;

@gahtan-syarif is this book somewhere online as part of a github repo?

**Comment by gahtan-syarif** [comment]
> > > how do the lines in the opening book look like?
> > 
> > 
> > rnb1kbnr/ppp1pppp/8/4q3/8/2N5/PPPP1PPP/R1BQKBNR w KQkq - hmvc 2; fmvn 4; rnbqkbnr/pp2pppp/2p5/8/2pP4/4P3/PP3PPP/RNBQKBNR w KQkq - hmvc 0; fmvn 4; rnbqk1nr/pppp1ppp/3b4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R b KQkq - hmvc 0; fmvn 3;
> 
> @gahtan-syarif is this book somewhere online as part of a github repo?

ahh sorry, didnt catch the mention, u already have the book i think, its the lichess book with movecounters

**Comment by robertnurnberg** [comment]
Probably the one that is created by the worker on the fly. (Something else we'll be able to drop after the transition to fast-chess).
