### ISSUE TITLE
insufficient material for position with two bishops of the same color and two kings

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#604]
![Screenshot 2024-07-17 224115](https://github.com/user-attachments/assets/1753ea06-e039-4f32-bec8-6722a2415c8a)

this position is a draw by insufficient material as both bishops are on the same color, cutechess correctly marked the position as a draw but fast-chess did not

**Comment by Disservin** [comment]
ah missed that when initially writing this, wikipedia is missing this case https://en.wikipedia.org/wiki/Draw_(chess)#:~:text=insufficient%20material%20to%20checkmate%20include%3A

just needs another check here

https://github.com/Disservin/chess-library/blob/master/src/board.hpp#L658
