### ISSUE TITLE
Stop Pgn Reader at 3fold

### ISSUE THREAD

**Issue by gahtan-syarif** [Disservin/fast-chess#607]
```
[Result "1/2-1/2"]

1. e4 Nc6 2. Nf3 d5 3. exd5 Qxd5 4. Nc3 Qd8 5. Nb1 Qd5 6. Ng1 Qd8 7. Nf3 Qd5 8. Nc3 Qa5 1/2-1/2
```

when specified `plies=16`  , cutechess would only parse it to `7. Nf3` while fastchess parses the full 8 moves. the reason cutechess stops prematurely is because `7. Qd5` is a 3fold repetition draw. should we do the same thing for fast-chess?

**Comment by vondele** [comment]
note that in general (e.g. for analysis) you'd like to be able to go past a 3-fold, it is just for the book lines this might make some sense.

**Comment by Disservin** [comment]
given that we stop at an illegal move https://github.com/Disservin/fast-chess/pull/642, this makes sense to also respect if the game is over and stop just right before
