### ISSUE TITLE
logger misses game results

### ISSUE THREAD

**Issue by robertnurnberg** [Disservin/fast-chess#614]
Not sure if this is intended behaviour:
```
> rm -f log.txt && ./fast-chess -engine cmd=../stockfish/src/stockfish name=sf1 -engine cmd=../stockfish/src/stockfish name=sf2 -each tc=1+0.1 -concurrency 1 -openings file=grob.epd -log file=log.txt level=trace -rounds 2 -games 1 -pgnout file=grob_sf_sf.pgn 
Warning: No opening book seed specified! Consider specifying one, otherwise the match will be played using the default seed of 951356066.
Indexing opening suite...
Started game 1 of 2 (sf1 vs sf2)
Finished game 1 (sf1 vs sf2): 1/2-1/2 {Draw by 3-fold repetition}
Started game 2 of 2 (sf2 vs sf1)
Finished game 2 (sf2 vs sf1): 0-1 {Black mates}
--------------------------------------------------
Results of sf1 vs sf2 (1+0.1, 1t, 16MB, grob.epd):
Elo: 190.85 +/- nan, nElo: 347.44 +/- 481.51
LOS: 92.14 %, DrawRatio: 50.00 %, PairsRatio: -nan
Games: 2, Wins: 1, Losses: 0, Draws: 1, Points: 1.5 (75.00 %)
--------------------------------------------------
Finished match
> grep " game" log.txt                        
[TRACE ] [18:01:41.206907] <fastchess> Playing game 1 between sf1 and sf2
[TRACE ] [18:02:08.106651] <fastchess> Playing game 2 between sf2 and sf1
```

I would expect to see game ending TRACE log in the logs.

**Comment by robertnurnberg** [comment]
Different weird logging behaviour (although probably because of a faulty engine) is reported in https://github.com/robertnurnberg/cdblib/pull/34#issuecomment-2241196038.

**Comment by Disservin** [comment]
I am not sure what this is tbh.. (can replicate this too)

started game is only ever written to stdout
```cpp
auto fmt = fmt::format("Started game {} of {} ({} vs {})\n", current_game_count, max_game_count, configs.white.name, configs.black.name);

std::cout << fmt << std::flush;
```

however the logs say that it was read from the engine..
`[Engine] [18:21:54.967227] <139687511123520> python-chess-engine ---> Started game 2 of 2 (python-chess-engine vs sf)`p

**Comment by Disservin** [comment]
this doesn't work
```
python ../python-chess-engine/src/main.py
```

this works
```
#!/bin/bash

python ../python-chess-engine/src/main.py
```

**Comment by vondele** [comment]
so maybe some differences between bash and the system sh when in comes to io ? It is definitely surprising.

**Comment by robertnurnberg** [comment]
Oh, interesting. Nice catch. However, fast-chess should behave more gracefully when things go wrong I think.

**Comment by Disservin** [comment]
https://github.com/Disservin/fast-chess/commit/48ce9aa9cfd5e194ccd2ac75705a84b19ff47ba0

should warn now about the engines not starting properly and also there should be start/stopped results with game results

**Comment by Disservin** [comment]
https://github.com/Disservin/fast-chess/commit/a74b034ec3d38b0ec873ccefd3ed784c2efdd5b9
