### ISSUE TITLE
-concurrency 1 leads to games played in parallel

### ISSUE THREAD

**Issue by robertnurnberg** [Disservin/fast-chess#622]
I observed that even though I set `-concurrency 1`, two games are played in parallel. This is also what the man/help seems to indicate.

This goes against the meaning in cutechess, and arguably what most users would expect.

**Comment by Disservin** [comment]
how did you observe that?

**Comment by robertnurnberg** [comment]
Sorry, can no longer reproduce. The man page would need an update then, it seems: In `Plays N matches concurrently. Default value is 1.` change matches to games.
