### ISSUE TITLE
Every game resulting in a draw

### ISSUE THREAD

**Issue by jonathanmcdermid** [Disservin/fast-chess#634]
https://github.com/jonathanmcdermid/Clovis/pull/21
https://github.com/jonathanmcdermid/Clovis/actions/runs/10054095058/job/27788039114

I'm trying to use fastchess in a pipeline, but despite using what appears to be a valid command, every game results in a draw. 

./fast-chess/fast-chess \
  -engine name=clovis-new cmd=build/bin/Release/clovis \
  -engine name=clovis-old cmd=build/clovis-release-gcc-linux \
  -games 100 \
  -each proto=uci tc=5+0.1 \
  -openings file=fast-chess/app/tests/data/openings.epd format=epd order=random \
  -concurrency 32 \
  -pgnout file=self-play.pgn

**Comment by Disservin** [comment]
This looks like the binary isn't working for the engines(probably a wrong path), the games dont have a termination end 
`Finished game 3 (clovis-new vs clovis-old): 1/2-1/2 {}`

```
[Event "Fast-Chess Tournament"]
[Site "?"]
[Date "2024.07.23"]
[Round "2"]
[White "clovis-new"]
[Black "clovis-old"]
[Result "*"]
[SetUp "1"]
[FEN "rnbq1rk1/ppp1ppbp/1n4p1/8/2BP4/2N1PN2/PP2QPPP/R1B2RK1 w - - 7 9"]
[GameDuration "00:00:00"]
[GameStartTime "2024-07-23T06:48:25 +0000"]
[GameEndTime "2024-07-23T06:48:26 +0000"]
[PlyCount "0"]
[TimeControl "5+0.1"]

 *
```

can you specify the the log option with `-log file=log.txt level=trace` and maybe upload to get a better understanding?

**Comment by robertnurnberg** [comment]
Technically, if the tournament starts and both binaries are not working, it should always be a loss for the side with the first move? But I know that engines not starting/not responding is going to be fixed soon, and the tournament then wouldn't even start, right?

**Comment by Disservin** [comment]
>  and the tournament then wouldn't even start, right?

yes

>  should always be a loss for the side with the first move?

probably

**Comment by Disservin** [comment]
@jonathanmcdermid 

the binary doesnt seem to work, i plan to improve how that is being displayed though

https://github.com/Disservin/Clovis/actions/runs/10063906096/job/27819705219?pr=1

**Comment by jonathanmcdermid** [comment]
@Disservin 
I'm not sure if this run you made is actually identifying the problem. bench isnt a valid command for that binary. This run shows how the binary is indeed where it is expected to be.
https://github.com/jonathanmcdermid/Clovis/actions/runs/10069623122/job/27836892752
Do you have any advice for determining what exactly is going wrong with the fastchess command?

**Comment by jonathanmcdermid** [comment]
@Disservin take a look at the log file. It seems that the engine is interfacing with fastchess just fine. Not sure what is going wrong.

https://github.com/jonathanmcdermid/Clovis/actions/runs/10069932635/artifacts/1733266219

**Comment by jonathanmcdermid** [comment]
`[Engine] [03:23:44.682683] <140336133305920> clovis-new ---> info depth 14 score cp   50 nodes   695027 time    376 nps  1843572 pv f1b5 b8d7 f3d4 a8c8 e4d5 f6d5 c2e2 d8e7 c3e4 e8d8 e1g1 d5f6 b5d7 f6d7 f1e1 b7e4 e2e4 e7e4 e1e4 
[Engine] [03:23:44.682688] <140336133305920> clovis-new ---> bestmove f1b5
[TRACE ] [03:23:44.682696] <140336133305920> fastchess --- Engine clovis-new is done thinking
[TRACE ] [03:23:44.682702] <140336133305920> fastchess --- Check if engine clovis-new is in a ready state
[TRACE ] [03:23:44.682712] <140336133305920> fastchess --- Pinging engine clovis-new
[Engine] [03:23:44.682717] <140336133305920> clovis-new <--- isready
[Engine] [03:23:44.682765] <140336133305920> clovis-new ---> readyok
[TRACE ] [03:23:44.682775] <140336133305920> fastchess --- Engine clovis-new is responsive.
[TRACE ] [03:23:44.682780] <140336133305920> fastchess --- Engine clovis-new is in a ready state
[TRACE ] [03:23:44.683652] <140336133305920> fastchess --- Game 1 between clovis-new and clovis-old finished
[TRACE ] [03:23:44.683687] <140336133305920> fastchess --- Game 1 finished with result *
[TRACE ] [03:23:44.683719] <140336133305920> fastchess --- Game 2 between clovis-old and clovis-new starting`
@Disservin It seems like every game just has one engine queried for the first move, and then ends for some reason.

**Comment by Disservin** [comment]
> I'm not sure if this run you made is actually identifying the problem.

Oh sorry

> And could you show me what a valid command would be in this pipeline

checkout sf ci


Id if the binary maybe crashes in the ci with the commands, ill look later again

**Comment by jonathanmcdermid** [comment]
Thanks for your help, I will try matching the sf ci more closely and also will try using a sf binary to determine if its a problem with my engine or not.

**Comment by Disservin** [comment]
I just realized that your engine has the output aligned
```
info depth 13 score cp   58 nodes   291609 time    153 nps  1893564 pv f1b5 b8d7 f3d4 a8c8 e4d5 f6d5 c2e2 f8e7 c3d5 b7d5 e2g4 e7f6 e1g1 f6e5 f1d1 
info depth 14 score cp   50 nodes   695027 time    376 nps  1843572 pv f1b5 b8d7 f3d4 a8c8 e4d5 f6d5 c2e2 d8e7 c3e4 e8d8 e1g1 d5f6 b5d7 f6d7 f1e1 b7e4 e2e4 e7e4 e1e4 
```

while this should still work, i can imagine that maybe fc doesnt correctly parse something

**Comment by jonathanmcdermid** [comment]
@Disservin thanks! that was indeed the problem. I will remove the alignment for now. Do you plan on making fc accomodate that sort of thing or no?

**Comment by Disservin** [comment]
yeah can you check if replacing the simple emplace_back here to the conditional work for you?
https://github.com/Disservin/fast-chess/blob/master/app/src/util/helper.hpp#L66

```
    while (std::getline(string_stream, segment, delimiter))
        if (!segment.empty()) seglist.emplace_back(segment);
```

(feel free to open a pr if it does)
