### ISSUE TITLE
Concurrency Speed

### ISSUE THREAD

**Issue by jonathanmcdermid** [Disservin/fast-chess#647]
I am trying to switch my pipeline from using cutechess to fastchess, and I think I have everything figured out except concurrency. I have set -concurrency 32 [here](https://github.com/jonathanmcdermid/Clovis/pull/21), but it still seems to take about 10x as long to finish 400 games as cutechess does with concurrency 32. I assume there must be something I'm doing wrong with my command? Draw adjudication rules arent identical but its not enough to make up the huge difference.

[Cutechess run example
](https://github.com/jonathanmcdermid/Clovis/actions/runs/10053164543/job/27785517205) (download takes a while, but games finish quick)

[Fastchess run example
](https://github.com/jonathanmcdermid/Clovis/actions/runs/10071737623/job/27842379425?pr=21)

fast-chess command

./fast-chess/fast-chess \
  -engine cmd=build/bin/Release/clovis name=clovis-new \
  -engine cmd=build/clovis-release-gcc-linux name=clovis-old \
  -each tc=5+0.1 \
  -openings file=fast-chess/app/tests/data/openings.epd format=epd order=random \
  -rounds 200 \
  -repeat \
  -concurrency 32 \
  -pgnout file=self-play.pgn \
  -draw movenumber=100 score=1000
  
cutechess command 
  
  ./build/cutechess-cli \
  -engine name=clovis-new cmd="../build/bin/Release/clovis" \
  -engine name=clovis-old cmd="../build/clovis-release-gcc-linux" \
  -each proto=uci tc=inf/5+0.1 \
  -games 2 -rounds 200 -repeat 2 -maxmoves 200 \
  -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 \
  -concurrency 32 \
  -resultformat "results - %s wins, %s draws, %s losses" > results.log
  
  (yes I know this is using SPRT, but even if it plays the full 400 games, it only takes around 5 minutes)

**Comment by gahtan-syarif** [comment]
If youre running this on the CI then the CI is limited to 4 threads, fastchess concurrency is capped to the number of hardware threads

**Comment by jonathanmcdermid** [comment]
@gahtan-syarif The github actions CI in general is limited to 4 threads? How does that explain why cutechess finishes so quickly then?

**Comment by gahtan-syarif** [comment]
> @gahtan-syarif The github actions CI in general is limited to 4 threads? How does that explain why cutechess finishes so quickly then?

Yes, the github actions CI is limited to 4 threads afaik. Cutechess i believe doesnt limit the concurrency to the number of threads, so in your case a single thread is managing 4 games at once (which is not ideal and can skew results)

**Comment by jonathanmcdermid** [comment]
I see, thank you!

**Comment by Disservin** [comment]
Id be curious to know the output of that cutechess run, I'd assume there are many time losses
