### ISSUE TITLE
Use a .JSON for settings

### ISSUE THREAD

**Issue by crippa1337** [Disservin/fast-chess#78]
For example:
```json
"openingbook":  {
    "plies": 0,
    "random": true, 
},
"games": 1,
"rounds": 1,
```

**Comment by SzilBalazs** [comment]
Currently a YAML configuration is being worked on #62 with the same functionality and a way to stop and resume tournaments.

**Comment by Disservin** [comment]
done with https://github.com/Disservin/fast-chess/pull/80 im happy to hear your feedback. It automatically saves the config after control c or if all the games have finished. Once you have a config you just start it like this
`fast-chess.exe -config config.json`
