### ISSUE TITLE
bug: fast-chess leaves lingering processes if crashed/killed

### ISSUE THREAD

**Issue by uwuplant** [Disservin/fast-chess#94]
please send help
![image](https://user-images.githubusercontent.com/26153075/225206283-f5bec2bb-f6fd-4915-aba2-ebfe8b0cd777.png)

**Comment by SzilBalazs** [comment]
Hello! Did you used the latest release or you manually built the current master?

**Comment by Disservin** [comment]
./fast-chess -version 
Prints the version btw

**Comment by uwuplant** [comment]
> Hello! Did you use the latest release or you manually built the current master?

version is `fast-chess 20230315-8afc828` (temporaryfix branch), but the same also occurs with master.

**Comment by SzilBalazs** [comment]
Previously I fixed this problem, but it was probably reintroduced with a later patch. Tomorrow I will take a look into it.

**Comment by Disservin** [comment]
Im not quite sure what @SzilBalazs did in the past but your engine should detect eof and close. See https://github.com/official-stockfish/Stockfish/blob/f0556dcbe3ba2fc804ab26d4552446602a75f064/src/uci.cpp#L229 . Also under which circumstances did this appear ? Always? Engine crash? fast-chess crash? Control C ?
